version: 2.1
executors:
  test:
    docker:
      - image: circleci/python:3.7
        user: root
jobs:
  build:
    executor:
      name: test
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.03.0-ce
      - run:
          name: up mysql
          command: |
            docker network create test_network
            docker run --name test_mysql --network test_network -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=test -d mysql:5.7
      - run:
          name: connect dummy container for volume
          command: |
            docker create -v / --name configs alpine:3.4 /bin/true
            docker cp ./schemaspy/test.properties configs:/
            docker run --volumes-from configs schemaspy/schemaspy:shapshot -rails
